// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Add/Adults": {
            "post": {
                "description": "Add a new adult",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Adults"
                ],
                "summary": "Add a new adult",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        },
        "/Add/Children": {
            "post": {
                "description": "Add a new child",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "Add a new child",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        },
        "/Adults": {
            "get": {
                "description": "Get a list of adults",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Adults"
                ],
                "summary": "Get all adults",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        },
        "/Adults/{id}": {
            "get": {
                "description": "Get a specific adult by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Adults"
                ],
                "summary": "Get adult by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Adult ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        },
        "/Children": {
            "get": {
                "description": "Get a list of children",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "Get all children",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        },
        "/Children/{id}": {
            "get": {
                "description": "Get a specific child by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Children"
                ],
                "summary": "Get child by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Child ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ApiGlobal",
	Description:      "API for managing Adults and Children",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
